spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:auth
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      show_sql: true
      format_sql: true

jwt:
  secret: 12345678901234567890123456789012